### ISSUE TITLE
Day 4 2020

### ISSUE THREAD

**Issue by David-Haley** [KenKarrasch/Adventofcode#1]
The hcl requirement to be six valid Hex digits, specifically lower case. Does your code accept any lower case characters. My code is potentially problematic because I have used the Ada runtime library Hexadecimal_Digit_Set which will allow for upper case 'A' .. 'F'.

The examples given do include letters other 'a' .. 'f'; your actual input must not or the passports with these errors were otherwise invalid.

**Comment by KenKarrasch** [comment]
Thanks Dave for the pickup.  Looks like there were a bunch of problems with the code. I have had a go at use regular expressions for practice.

problems found with the original solution:

#  - did not detect hex numbers correctly (#123abz was counted as a valid solution)
# - did not check year numbers had exactly four digits
# - did not check height record had 'in' and 'cm' at the end ('cm190' may have been incorrectly counted as a valid input)
# - did check that haircolor had 6 hexdigits

# - part one is still dodgy
